pipeline {
    agent any

    stages {
        stage('Pull Code') {
            steps {
                checkout scm
            }
        }
        stage('Unit testing') {
            steps {
                echo 'asdasdasd'
            }
        }
        stage('Component testing') {
            steps {
                echo 'asdasdasd'
            }
        }
        stage('Packaging') {
            steps {
                echo 'asdasdasd'
            }
        }
        stage('Deploy to target server') {
            steps {
               echo 'asdasdasd'
            }
        }
        stage('API/UI testing') {
            steps {
                echo 'asdasdasd'
    }
}